version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "=== INSTALLING DEPENDENCIES ==="
      - pip install --upgrade pip
      - pip install boto3 sagemaker pandas scikit-learn joblib numpy

  build:
    commands:
      - echo "=== BUILD STARTED - VERSION 2025-11-27-FINAL ==="
      - echo "Current working directory:"
      - pwd
      - echo "Directory contents:"
      - ls -la
      - echo "Searching for Pipeline directory:"
      - find . -name "Pipeline" -type d -ls
      - echo "=== RUNNING MLOPS PIPELINE ==="
      - python Pipeline/sagemaker_pipeline.py
      - echo "=== PIPELINE COMPLETED ==="

  post_build:
    commands:
      - echo "=== POST BUILD COMPLETED ==="