version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "📤 Uploading data and code to S3..."
      - aws s3 cp data.csv s3://teamars-1ee00834/data/data.csv
      - echo "📦 Creating source code tarball..."
      - tar -czf source.tar.gz code/
      - aws s3 cp source.tar.gz s3://teamars-1ee00834/code/source.tar.gz
      - echo "✅ Data and code uploaded to S3"
      - echo "🚀 Starting SageMaker Training Job..."
      - python Pipeline/sagemaker_pipeline.py
      - echo "✅ Training job started. Check SageMaker Console for progress."

artifacts:
  files:
    - '**/*'