version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "📤 Uploading data and code to S3..."
      - aws s3 cp data.csv s3://teamars/data/data.csv
      - aws s3 cp --recursive code/ s3://teamars/code/
      - echo "✅ Data and code uploaded to S3"
      - echo "🚀 Starting SageMaker Training Job..."
      - python Pipeline/sagemaker_pipeline.py
      - echo "✅ Training job started. Check SageMaker Console for progress."

artifacts:
  files:
    - '**/*'